[patterns]
    [patterns.p4]

    [patterns.default]

    [patterns.default.arpeggios]

        [patterns.default.arpeggios.default]
        # (string_num, chord degree (1-indexed))
        pos1=[[0,1], [0, 3], [-1, 5], [-2, 7], [-2,1]]
        pos2=[[0,1], [-1, 3], [-1, 5], [-2, 7], [-2, 1]]
        pos3=[[0,1], [-1, 3], [-2, 5], [-2, 7], [-3, 1]]

        [patterns.default.arpeggios.b9]
        # (string_num, chord degree (1-indexed))
        pos1=[[0,1], [0, 2], [0, 3], [-1, 5], [-2, 7], [-2,1]]
        pos2=[[0,1], [0, 2], [-1, 3], [-1, 5], [-2, 7], [-2, 1]]
        pos3=[[0,1], [0, 2], [-1, 3], [-2, 5], [-2, 7], [-3, 1]]

    [patterns.default.scales]

        [patterns.default.scales.defalt]

        pos1=[[0,1], [0, 2], [0, 3], [-1, 4], [-1, 5], [-1, 6], [-2, 7], [-2,1]]
        pos2=[[0,1], [0, 2], [-1, 3], [-1, 5], [-1, 5], [-2, 6], [-2, 7], [-2, 1]]
        pos3=[[0,1], [-1, 2], [-1, 3], [-1, 4], [-2, 5], [-2, 6], [-2, 7], [-3, 1]]