[systems]
major=[0,2,4,5,7,9,11]
melodic_minor=[0,2,3,5,7,9,11]
harmonic_minor=[0,2,3,5,7,8,11]
diminished=[0,1,3,4,6,7,9,10]
whole_tone=[0,2,4,6,8,10]

[scales]
bebop_dominant=['0','2','4','5','7','10','(11)']
augmented=['0','3','4','7','8','10']
blues=['0','3','5','(6)','7','10']
#altered_scale=[0,1,3,4,6,8,10]
